### ISSUE TITLE
Attempting to remove a dimension crashes the game while saving.

### ISSUE THREAD

**Issue by Alceris** [iPortalTeam/DimLib#5]
I added a new dimension via chat command, didn't want it anymore so I removed it, however at that point doing anything that makes the game save (such as pausing) crashes, and then when I go back into the world the dimension is not removed. Fabric version 0.16.7, Minecraft version 1.21.1

**Comment by qouteall** [comment]
Can you post the crash report

**Comment by Alceris** [comment]
Not without just pasting the text into a comment, assuming this broken website will even let me do that much.

**Comment by Alceris** [comment]
Since I can't put the actual file in here, here's what seems like probably the most relevant part, the rest is just system details.

java.lang.NullPointerException: Exception in server tick loop
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:179)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at knot//it.unimi.dsi.fastutil.objects.ObjectArrayList$Spliterator.forEachRemaining(ObjectArrayList.java:955)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at knot//net.minecraft.class_7723.<init>(class_7723.java:62)
	at knot//net.minecraft.class_7726.method_45539(class_7726.java:24)
	at knot//net.minecraft.class_31.method_158(class_31.java:256)
	at knot//net.minecraft.class_31.method_163(class_31.java:233)
	at knot//net.minecraft.class_32$class_5143.method_27426(class_32.java:452)
	at knot//net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:563)
	at knot//net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:580)
	at knot//net.minecraft.class_1132.method_39218(class_1132.java:318)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:96)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Nick1st** [comment]
This might be a bit late, but you can upload your (crash-)log to gist.github.com
